### ISSUE TITLE
有没有什么方法可去除pyim-wbdict-v86.pyim中的繁体字

### ISSUE THREAD

**Issue by lld2001** [tumashu/chinese-pyim-wbdict#13]
几乎不会输入繁体字，使用pyim-wbdict-v86.pyim词库时，繁体重码太多。

或者有没有哪个开源的五笔词库可以拿来转换成 pyim 可用的

**Comment by tumashu** [comment]
词库是其他同学贡献的，我是五笔外行。。。

**Comment by lld2001** [comment]
我找了个五笔的词库，只要保证前面有wubi/就行了吗？

**Comment by tumashu** [comment]
嗯，确保是utf-8-unix格式，pyim自带一个词库管理器，你可以不安装这个包，然后用词库管理器添加词库文件

**Comment by tumashu** [comment]
pyim-dicts-manager

**Comment by lld2001** [comment]
好的，我摸索下看看。我打算整个弄个新的词库。

**Comment by lld2001** [comment]
可以了，从  http://gaokuan.ys168.com/  找了个极爽五笔的词库。没有了繁体重码的烦恼，感觉打字更快了。在我的 fork 下。
