### ISSUE TITLE
Package renames and removals

### ISSUE THREAD

**Issue by tarsius** [tumashu/chinese-pyim-wbdict#2]
I noticed that you have renamed your `chinese-pyim-*` packages to just `pyim-*`. I have updated Melpa and the Emacsmirror accordingly.

I also noticed that you have remove the `chinese-remote-input` repository, but could not find a replacement. What happened here?

**Comment by tarsius** [comment]
The repositories for your packages `sql-mssql`, `ebib-handy`, `easy-lentic`, `bbdb-handy`, `bbdb-china`, and `bbdb-android` have also disappeared. Why where they removed?

**Comment by tumashu** [comment]
because they seem to useless for me and I can not find people to maintain them, so I decide remove them from melpa,   I will send pull request to melpa

**Comment by tumashu** [comment]
Another approach is  switching recipes to emacsmirror.

**Comment by tumashu** [comment]
1. sql-mssql, ebib-handy,  bbdb-china 's code too hacky
2. easy-lentic can be replaced by el2org
3. bbdb-handy's feature is in ebdb now, and I have switched to ebdb, for it support chinese well very much.

**Comment by tarsius** [comment]
I think it is best to remove them.

**Comment by tumashu** [comment]
I thinks so

**Comment by tarsius** [comment]
Same applies to `chinese-remote-input`, right?

**Comment by tumashu** [comment]
Yes, chinese-remote-input may have no user :-)

**Comment by tarsius** [comment]
I have moved these packages from the Emacsmirror to the Emacsattic. Have you already started working on removing them from Melpa. If not, then I can do that; I have commit rights.

**Comment by tumashu** [comment]
If you have time, just do it,  I have to do it after 21:00 ...

**Comment by tarsius** [comment]
Done :wink:

**Comment by tumashu** [comment]
thanks very much 👍

**Comment by tarsius** [comment]
You are welcome!

May I suggest that in the future you wait a little before adding a new package to Melpa? :stuck_out_tongue_closed_eyes:

**Comment by tumashu** [comment]
```
May I suggest that in the future you wait a little before adding a new package to Melpa? 😝
```
Good idea, my main job in the future may maintain cnfonts and pyim,

**Comment by tarsius** [comment]
I sometimes get the impression that people add mostly private packages on Melpa because they have grown so accustomed to the comfort provided by `package.el`. But there are other methods of installing your own packages without having to go that route, including [Quelpa](https://github.com/quelpa/quelpa), my [borg](https://github.com/emacscollective/borg) (I intend to teach it to work alongside `package.el` in the future), and simply using `(add-to-list 'load-path ...)` explicitly. I might blog about that at a later time.

**Comment by tumashu** [comment]
```
 mostly private packages on Melpa because they have grown so accustomed to the comfort provided by package.el. 
```
This is true, most packages are derived from my own emacs config, I want to share some independent feature i code with other people, so I reorganize them as packages,  the fact is that nearly no other people use them 。。。

At the moment,  only pyim, cnfonts and org-webpage have many users :-(

Maybe it my wrong.....
